[package]
name = "nightcycle/option"
description = "A basic port of the rust Option class"
version = "0.2.0"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
